---
  - name: Creating the Filebeat Installation Playbook
    hosts: webservers
    become: true
    tasks:

      # Use command module to download filebeat
    - name: Download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

      # Use command module to install filebeat
    - name: Install filebeat deb
      command: dpkg -i filebeat-7.4.0-amd64.deb

      # Use copy module to configure filebeat
    - name: Drop in filebeat.yml
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

      # Use command module to enable and configure docker module for filebeat
    - name: Enable and configure system module
      command: filebeat modules enable system

      # Use command module to setup filebeat
    - name: Setup filebeat
      command: filebeat setup

      # Use command module to start filebeat service
    - name: Start filebeat service
      command: service filebeat start

      # Use systemd module to enable filebeat service on boot
    - name: Enable service filebeat on boot
      systemd:
        name: filebeat
        enabled: yes
