---
  - name: Installation playbook for Elk server
    hosts: elk
    become: true
    tasks:

      # Use ansible.posix.sysctl module to set vm.max_map_count to 262144
    - name: Set the vm.max_map_count to 262144
      ansible.posix.sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present

      # Use apt module to install docker.io
    - name: Install docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

      # Use apt module to install python3-pip
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        update_cache: yes
        name: python3-pip
        state: present

      # Use pip module to install docker
    - name: Install docker
      pip:
        name: docker
        state: present

      # Download docker_container called sebp/elk:761 published on ports
      # 5601, 9200, 5044
    - name: Install sebp/elk:761
      docker_container:
        name: sebp
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044

      # Use systemd module to enable docker service
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
